# Generated by Django 5.2.3 on 2025-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField(default=0)),
                ('product_discount_price', models.FloatField(default=0)),
                ('product_rate', models.FloatField(default=0)),
                ('review_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
