# Generated by Django 5.2.3 on 2025-06-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-parsed_at'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='parsed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='parsed at'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='reviews count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='product discount price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='product_rate'),
        ),
    ]
